name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: d9b4f647d88f194779c240cd59d86304bfd8c0f8
    - name: support ape bins 1
      run: sudo cp build/bootstrap/ape.elf /usr/bin/ape

    - name: support ape bins 2
      run: sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

